import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[font]
size = 10.0
  [font.normal]
  family = "ComicCode"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[keyboard]
bindings = [
{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
